name: ci
on:
  push:
    branches:
      - main
  pull_request:
    types: 
      - opened
      - synchronize
      - reopened
env:
  MAKEFLAGS: "-j 8"
  PRIVATE_REGISTRY_HOST: us.gcr.io
  PRIVATE_REGISTRY_URL: us.gcr.io/buf-private-gcr-1
permission:
  contents: read
jobs:
  testlint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup-go
        if: success()
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.x
      - name: make-test
        if: success()
        run: make test && make checkgenerate
      - name: make-lint
        run: make lint
  docker-build-push-connect-demo:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs:
      - testlint
    steps:
      - name: setup-docker-buildx
        uses: docker/setup-buildx-action@v2
      - name: login-gcr
        uses: docker/login-action@v2
        with:
          registry: ${{ env.PRIVATE_REGISTRY_HOST }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.PRIVATE_DOCKER_TOKEN }}
      - name: build-push
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile
          push: true
          tags: |
            ${{ env.PRIVATE_REGISTRY_URL }}/connect-demo:latest
            ${{ env.PRIVATE_REGISTRY_URL }}/connect-demo:${{ github.sha }}
